name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "51 */4 * * *" # Every 4 hours
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
            - uses: k2bd/advent-readme-stars@v1
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v4
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  commit_message: "update readme progess"
